#! /bin/sh 
# Purpose: change the title in an vt or xterm - @G.Alves
if [ $# -eq 0 ]; then
 r=""
 which root-config > /dev/null 2>& 1
 if [ $? -eq 0 ]; then
   r=`root-config --version`;
 fi
 t=""
 d=""
 v=""
 c=""
 s=""
 e="-ne"
 if test ! "x$USE_CVMFS" = "x"; then
     c="_cvmfs"
 fi
 if test ! "x$SPACK_ROOT" = "x"; then
     s="_spack"
 fi
# if test ! "x$ROOT_LEVEL" = "x"; then
#  r=$ROOT_LEVEL
# fi
 if test ! "x$STAR_HOST_SYS" = "x"; then
  t=$STAR_HOST_SYS
if [[ $STAR_HOST_SYS  == amd* ]]; then
   e=""
fi
 fi
 if test ! "x$STAR_LEVEL" = "x"; then
  v=$STAR_LEVEL
 fi
 if test ! "x$NODEBUG" = "x"; then
  d=opt
  if test "x$NODEBUG" = "x-O3"; then
  d=opt3
  fi
 else 
  d=debug
 fi
 TNAME=${r}_${v}_${t}_${d}${c}${s}
 TNAMET=`hostname -s`_${TNAME}
else
 TNAMET=$1
 TNAME=$1
fi
# Begin source code.
case $TERM in
 xterm|vt100|vt220|xterms|aixterm|xterm*)          # vt100 tool
   if test "x$e" = "x" ; then
 echo  $e "]1;${TNAMET}\c"
 echo  $e "]0;${TNAMET}\c"
   else
 echo  -ne "]1;${TNAMET}"
 echo  -ne "]0;${TNAMET}"
   fi
 ;;

 *)
 echo "Unknown terminal: $term"
 ;;

esac
